# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
SECRET_TOKEN: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

# If you want to try sending email locally, you'll need make an AWS account and populate these values
# It's easier to just use Mailcatcher and Mailer previews, though!
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
AWS_REGION: us-west-2


# Be sure to include a space between the colon and the key/secret!
GITHUB_CLIENT_KEY:
GITHUB_CLIENT_SECRET:

# For Google OAuth
GOOGLE_CLIENT_ID:
GOOGLE_CLIENT_SECRET:
